export const nigeriaLocations = {
    states: [
        "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno",
        "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT - Abuja", "Gombe",
        "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos",
        "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto",
        "Taraba", "Yobe", "Zamfara"
    ],
    cities: {
        "Lagos": ["Ikeja", "Lekki", "Victoria Island", "Ikoyi", "Surulere", "Yaba", "Ajah", "Ikorodu", "Agege", "Oshodi", "Festac", "Apapa"],
        "FCT - Abuja": ["Garki", "Wuse", "Maitama", "Asokoro", "Gwarinpa", "Kubwa", "Lugbe", "Jabi", "Utako"],
        "Rivers": ["Port Harcourt", "Obio-Akpor", "Bonny", "Degema", "Eleme", "Ikwerre", "Okrika"],
        "Oyo": ["Ibadan", "Ogbomosho", "Oyo", "Iseyin"],
        "Kano": ["Kano Municipal", "Fagge", "Dala", "Gwale", "Tarauni", "Nassarawa"],
        "Kaduna": ["Kaduna North", "Kaduna South", "Zaria", "Kafanchan"],
        "Enugu": ["Enugu North", "Enugu South", "Nsukka", "Agbani"],
        "Delta": ["Warri", "Asaba", "Sapele", "Ughelli"],
        "Ogun": ["Abeokuta", "Ijebu-Ode", "Sagamu", "Ota"],
        "Edo": ["Benin City", "Ekpoma", "Auchi"],
        "Anambra": ["Awka", "Onitsha", "Nnewi"],
        "Imo": ["Owerri", "Orlu", "Okigwe"],
        // Fallback for other states - generic list or main capital usually
        "Abia": ["Umuahia", "Aba"],
        "Adamawa": ["Yola", "Mubi"],
        "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene"],
        "Bauchi": ["Bauchi", "Azare"],
        "Bayelsa": ["Yenagoa"],
        "Benue": ["Makurdi", "Gboko", "Otukpo"],
        "Borno": ["Maiduguri", "Jere"],
        "Cross River": ["Calabar", "Ogoja", "Ikom"],
        "Ebonyi": ["Abakaliki"],
        "Ekiti": ["Ado-Ekiti", "Ikere"],
        "Gombe": ["Gombe"],
        "Jigawa": ["Dutse", "Hadejia"],
        "Katsina": ["Katsina", "Funtua", "Daura"],
        "Kebbi": ["Birnin Kebbi", "Argungu"],
        "Kogi": ["Lokoja", "Okene"],
        "Kwara": ["Ilorin", "Offa"],
        "Nasarawa": ["Lafia", "Keffi"],
        "Niger": ["Minna", "Bida", "Suleja"],
        "Ondo": ["Akure", "Ondo Town", "Owo"],
        "Osun": ["Osogbo", "Ile-Ife", "Ilesa"],
        "Plateau": ["Jos"],
        "Sokoto": ["Sokoto"],
        "Taraba": ["Jalingo"],
        "Yobe": ["Damaturu", "Potiskum"],
        "Zamfara": ["Gusau"]
    } as Record<string, string[]>
};
